### ISSUE TITLE
Needs to be updated

### ISSUE THREAD

**Issue by Rayvenhaus** [faiyazalam/user-login-history#1]
Causes an error with the latest version of Wordpress

**Comment by RickH64** [comment]
Same here (WordPress 4.7.1)...Deactivated the user-login-history plugin.

**Comment by faiyazalam** [comment]
guys, could you please tell me the error?
if possible, please share the screenshot.

**Comment by Rayvenhaus** [comment]
WHen it is actiavted, I get a blank page on log in.

**Comment by faiyazalam** [comment]
I have checked this plugin(v1.4) with WordPress 4.7.1 and 4.7.2 and it is working fine. I did not get blank page after activating the plugin.

**Comment by Rayvenhaus** [comment]
Must be a conflict with another plugin I am usings, your plugin and the current version of Wordpress

**Comment by faiyazalam** [comment]
I would like to request you to enable the debug mode and then activate the plugin and then let me know the error if it shows the error.
