### ISSUE TITLE
This isn't an issue but an idea for you

### ISSUE THREAD

**Issue by joelpeterson** [faiyazalam/user-login-history#2]
Hey I love your plugin here..... I have an idea for you.  I sell high end memberships and sometimes we get fraudulent orders but we don't know for months as we get a chargeback on our merchant account.  Usually someone orders with a stolen card, accesses the product for months sometimes and when the card owner finds out about it they call their bank.

You should make plugins for different membership solutions to detect if the billing information and login don't match.  For example many times the credit card is in the USA but the thief logs in from China or another country.  Perhaps your software could send out alerts if it suspected potential fraud?  For example I use Woocomerce.  A plugin like this would have saved my company over $10,000 just in the last 4 months alone..... there is a BIG need for this and I bet you could sell a bunch :)

**Comment by faiyazalam** [comment]
@joelpeterson Hi, thanks for your idea. I will definitely build plugin with the feature that you mentioned in your idea.
thanks once again.

**Comment by faiyazalam** [comment]
No to be fixed.
