### ISSUE TITLE
On PHP7, eregi() cause PHP fatal error

### ISSUE THREAD

**Issue by sshida** [faiyazalam/user-login-history#3]
--- lib/functions.php.orig      2017-02-24 15:12:14.362703896 +0000
+++ lib/functions.php   2017-02-24 15:12:22.610958642 +0000
@@ -103,7 +103,8 @@
 
     foreach ($browsers as $browser => $pattern) {
 
-        if (eregi($pattern, $userAgent)) {
+        $pattern = "/$pattern/i";
+        if (preg_match($pattern, $userAgent)) {
             return $browser;
         }
     }

**Comment by Kuzovlev-Sanya** [comment]
$browsers = array(
        'Opera' => '/Opera/',
        'Firefox' => '/(Firebird)|(Firefox)/',
        'Galeon' => '/Galeon/',
        'Chrome' => '/Chrome/',
        'MyIE' => '/MyIE/',
        'Lynx' => '/Lynx/',
        'Netscape' => '/(Mozilla\/4\.75)|(Netscape6)|(Mozilla\/4\.08)|(Mozilla\/4\.5)|(Mozilla\/4\.6)|(Mozilla\/4\.79)/',
        'Konqueror' => '/Konqueror/',
        'SearchBot' => '/(nuhk)|(Googlebot)|(Yammybot)|(Openbot)|(Slurp\/cat)|(msnbot)|(ia_archiver)/',
        'Internet Explorer 8' => '(MSIE 8\.[0-9]+)',
        'Internet Explorer 9' => '(MSIE 9\.[0-9]+)',
        'Internet Explorer 7' => '(MSIE 7\.[0-9]+)',
        'Internet Explorer 6' => '(MSIE 6\.[0-9]+)',
        'Internet Explorer 5' => '(MSIE 5\.[0-9]+)',
        'Internet Explorer 4' => '(MSIE 4\.[0-9]+)',
    );

**Comment by Kuzovlev-Sanya** [comment]
`if (preg_match($pattern, $userAgent)) {
            return $browser;
        }`

**Comment by faiyazalam** [comment]
fixed.
