### ISSUE TITLE
Not detected browser Edge and Safari

### ISSUE THREAD

**Issue by sshida** [faiyazalam/user-login-history#4]
--- lib/functions.php.orig      2017-02-24 15:12:14.362703896 +0000
+++ lib/functions.php   2017-02-24 15:59:35.070392844 +0000
@@ -87,7 +87,9 @@
         'Opera' => 'Opera',
         'Firefox' => '(Firebird)|(Firefox)',
         'Galeon' => 'Galeon',
+        'Edge' => 'Edge',
         'Chrome' => 'Chrome',
+        'Safari' => 'Safari',
         'MyIE' => 'MyIE',
         'Lynx' => 'Lynx',
         'Netscape' => '(Mozilla/4\.75)|(Netscape6)|(Mozilla/4\.08)|(Mozilla/4\.5)|(Mozilla/4\.6)|(Mozilla/4\.79)',

**Comment by faiyazalam** [comment]
Updated the code.
